name: tagging
description: call workflows for labels and semver

on:
  pull_request:
    types: [labeled, unlabeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labels:
    uses: ./.github/workflows/labels.yml
    secrets: inherit
      #token: ${{ secrets.GITHUB_TOKEN }}

  echo:
    runs-on: ubuntu-latest
    needs: labels
    steps:
      - run: |
          echo ${{ needs.labels.outputs.label }}
          # version=$(echo "${{ env.PR_LABEL_LIST}}"
          # echo "SEMVER=$version" >> $GITHUB_ENV

  semver:
    name: semver
    needs: labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: semantic versioning
        if: ${{ needs.labels.outputs.label != '' }}
        id: semver
        uses: ./.github/actions/semver
        with:
          version-bump: ${{ needs.labels.outputs.label }}
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: docker
    needs: [ semver, labels ]
    if: ${{ needs.labels.outputs.label != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: build image
        id: build
        run: echo build
      - name: deploy to ecr
        run: echo deploy
  
  wiz:
    name: wiz
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: scan image
        id: scan
        run: echo build
      - name: sign image
        run: echo sign

  deploy:
    name: deploy
    needs: wiz
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: deploy
        run: echo deploy
